name: Validate Renovate config

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json

jobs:
  validate:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/renovate.yml@7da7a169447c9249b1276a9361332bed080e57cd
