name: Security checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security:
    permissions:
      contents: read
      pull-requests: write
    uses: shuymn/github-actions/.github/workflows/security.yml@7da7a169447c9249b1276a9361332bed080e57cd
